setwd("D:/Rcode/exdata-data-household_power_consumption")
file <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
subfile <- subset(file, Date == "1/2/2007" | Date == "2/2/2007")
png("plot3.png")
x <- as.numeric(as.character(subfile[,7]))
y <- as.numeric(as.character(subfile[,8]))
z <- as.numeric(as.character(subfile[,9]))
dateTime <- as.POSIXlt(paste(as.Date(subfile$Date, format="%d/%m/%Y"), subfile$Time, sep=" "))
plot(dateTime, x,type="l",col = "black",ylab="Energy sub metering")
lines(dateTime, y,type="l",col = "red")
lines(dateTime, z,type="l",col = "blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),fil=c("black","red","blue"))

dev.off()
