setwd("D:/Rcode/exdata-data-household_power_consumption")
file <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
subfile <- subset(file, Date == "1/2/2007" | Date == "2/2/2007")
png("plot4.png")
opar <- par(no.readonly=TRUE)
par(mfrow=c(2,2))
x1 <- as.numeric(as.character(subfile[,3]))
dateTime <- as.POSIXlt(paste(as.Date(subfile$Date, format="%d/%m/%Y"), subfile$Time, sep=" "))
plot(dateTime, x1,type="l",ylab="Global Active Power(kilowatts)")
x2 <- as.numeric(as.character(subfile[,5]))
plot(dateTime, x2,type="l",ylab="Voltage")
x3 <- as.numeric(as.character(subfile[,7]))
y3 <- as.numeric(as.character(subfile[,8]))
z3 <- as.numeric(as.character(subfile[,9]))
plot(dateTime, x3,type="l",col = "black",ylab="Energy sub metering")
lines(dateTime, y3,type="l",col = "red")
lines(dateTime, z3,type="l",col = "blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),fil=c("black","red","blue"))
x4 <-as.numeric(as.character(subfile[,4]))
plot(dateTime, x4,type="l",ylab="Global_reactive_power")
dev.off()
